### ISSUE TITLE
[Docs] Add docs regarding `filesystem` and `global` environments

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1349] opened 2022-06-28 14:33 UTC
The environment names for `filesystem` and `default` leads to some misconception about what these environments are used for and how they can be managed. We need to create some documentation around what they are, how they’re used, and what they mean.

**Comment by trallard** [comment] 2022-06-30 14:42
TODO:

- [ ] renaming of `filesystem` `default` 
- [ ] update docs as needed

**Comment by viniciusdc** [comment] 2022-07-12 13:13
We found a bug within conda-store that was blocking the proposed changes, this was fixed in https://github.com/Quansight/conda-store/pull/346. This issue is blocked until the latest version of conda-store is integrated on Nebari.

**Comment by pavithraes** [comment] 2023-04-22 19:26
Closing as a duplicate of https://github.com/nebari-dev/nebari-docs/issues/80

**Closed by pavithraes** 2023-04-22 19:26 UTC
Labels: area: user experience 👩🏻‍💻, type: maintenance 🛠, type: release 🏷, type: duplicate 👯‍♀️
