### ISSUE TITLE
[BUG] - VS Code does not show theme images on start screen

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/nebari#2389] opened 2024-04-10 14:10 UTC
### Describe the bug

![image](https://github.com/nebari-dev/nebari/assets/5832902/b0e056f4-8fb4-4091-a422-7f2f0b236e37)

There are some reports of this upstream:

- https://github.com/coder/code-server/issues/4483 (2021, closed as fixed)
- https://github.com/microsoft/vscode/issues/180853 (2023, open)

### Expected behavior

No broken images on first page shown to the user. We can either provide a custom nebari-specific walkthrough or work with upstream to fix this.

### OS and architecture in which you are running Nebari

v2024.3.3

### How to Reproduce the problem?

Open VS Code for the first time

If you already opened it before you can click on menu (hamburger icon) → Help → Get Started → Click on the first walkthough or use command palette to find "Get Started" walk-though 

### Compute environment

None

**Comment by ericdatakelly** [comment] 2024-04-11 22:13
I just started up Onyx, which we just upgraded to Nebari 2024.3.3, and I see the images.

<img width="828" alt="image" src="https://github.com/nebari-dev/nebari/assets/24855669/fde0fb6b-095c-4b41-b0a2-54cded13c110">

**Comment by viniciusdc** [comment] 2024-04-12 13:19
Thanks for the follow-up, @ericdatakelly. If I remember correctly, Onys is a variant of Nebari with some custom changes. Can you double-check to see if they are not using some custom images there? The reason I ask is to evaluate if they have the same code-server version pinned.

**Comment by ericdatakelly** [comment] 2024-04-12 23:40
Hey @viniciusdc.  Yes, Onyx is built on top of Nebari and has custom features.  I'll ask about custom images, but for now I got this from the VS Code 'about':
```
code-server: v4.5.1
Code: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-07-19T16:29:15.252Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
```

**Comment by ericdatakelly** [comment] 2024-04-15 13:55
@viniciusdc We think it could be 'email address usernames', which have a special character `@`.  On our Onyx instance, our accounts have no special characters.  When we create an account with an email address for the user name, the links break.

**Comment by krassowski** [comment] 2024-04-17 13:53
Of note v4.5.1 is pretty old. The latest version is v4.23.1.

Maybe we should check if this is solved in the latest version? I think this would require bumping the version in the docker image installation script [here](
https://github.com/nebari-dev/nebari-docker-images/blob/6fe731e8a0daecc8baa4f046db10dca18a4b196d/scripts/install-code-server.sh#L8).

**Comment by viniciusdc** [comment] 2024-04-17 16:07
>
@viniciusdc We think it could be 'email address usernames', which have a special character @. On our Onyx instance, our accounts have no special characters. When we create an account with an email address for the user name, the links break.

This is indeed intriguing. As @krassowski suggested and considering past issues in earlier versions, I recommend first updating to the latest version to see if the problem persists. There don't seem to be any drawbacks to upgrading the current version. 

Also, by applying their PR bump, we can test the new version in a test profile, which helps us determine if the issue (related to old versions and Keycloak usernames) still exists.

**Comment by viniciusdc** [comment] 2024-04-17 16:25
This is really curious indeed, I was able to reproduce the issue, indeed for some reason the static files endpoint is not correctly fetched when the username contains the `@`:

**- Username: testuser**
![Captura de tela de 2024-04-17 13 20 26](https://github.com/nebari-dev/nebari/assets/51954708/b6f72540-7d03-46a5-be19-9e3485a2f157)
**- Username: testuser@***.neb**
![Captura de tela de 2024-04-17 13 23 22](https://github.com/nebari-dev/nebari/assets/51954708/45ab9133-9c46-48ef-b966-efe94362754f)
ari.dev

**Comment by viniciusdc** [comment] 2024-04-17 16:54
@ericdatakelly can you try asking them to create a profile using this image `quay.io/nebari/nebari-jupyterlab:bump-codeserver-version`, and test if that fixes the issue there as well?

**Comment by viniciusdc** [comment] 2024-04-17 16:55
for example:
```yaml
- display_name: Micro Instance (Custom)
      access: yaml
      groups:
        - developer
        - admin
      description: Stable environment with 0.5-1 cpu / 0.5-1 GB ram
      kubespawner_override:
        image: [quay.io/nebari/nebari-jupyterlab:bump-codeserver-version](http://quay.io/nebari/nebari-jupyterlab:bump-codeserver-version)
        cpu_limit: 1
        cpu_guarantee: 0.5
        mem_limit: 1G
        mem_guarantee: 0.5G
```

**Comment by ericdatakelly** [comment] 2024-04-17 16:58
Will do

**Comment by Adam-D-Lewis** [comment] 2024-05-02 17:20
@ericdatakelly  @viniciusdc It seems like this might be resolved now.  Can we close this issue?

**Comment by ericdatakelly** [comment] 2024-05-02 17:40
I think so.  I can see the images now and the code server version is 4.23.1.  Nebari version is 2024.4.1.

**Comment by Adam-D-Lewis** [comment] 2024-05-02 17:55
Great, feel free to reopen if needed. :+1:

**Closed by Adam-D-Lewis** 2024-05-02 17:55 UTC
Labels: type: bug 🐛, area: integration/code-server
