### ISSUE TITLE
User node group will not scale to zero nodes on Azure

### ISSUE THREAD

**Issue by tjcrone** [nebari-dev/nebari#1467] opened 2022-09-22 12:27 UTC
### OS system and architecture in which you are running QHub

Mac M1

### Expected behavior

When `min_nodes: 0` in the user node group I expect the node group to scale to zero nodes when there is no active user.

### Actual behavior

When there is no active user notebook, the user node group stays up with one node, and these pods running:

```
NAMESPACE      NAME                                   PF   READY     RESTARTS STATUS         CPU    MEM    %CPU/R    %CPU/L    %MEM/R    %MEM/L IP             NODE                             AGE
dev            qhub-prometheus-node-exporter-7dj6b    ●    1/1              0 Running          4     20       n/a       n/a       n/a       n/a 10.224.0.5     aks-user-41209954-vmss000003     38h
dev            user-scheduler-8f67c547d-gkxfv         ●    1/1              0 Running          2     21       n/a       n/a       n/a       n/a 10.244.9.2     aks-user-41209954-vmss000003     39h
dev            user-scheduler-8f67c547d-qjbt6         ●    1/1              0 Running          3     21       n/a       n/a       n/a       n/a 10.244.9.3     aks-user-41209954-vmss000003     39h
kube-system    azure-ip-masq-agent-v4zjf              ●    1/1              0 Running          1     16         1         0        32         6 10.224.0.5     aks-user-41209954-vmss000003     38h
kube-system    cloud-node-manager-58cx8               ●    1/1              0 Running          1     20         2         0        41         4 10.224.0.5     aks-user-41209954-vmss000003     38h
kube-system    csi-azuredisk-node-vv9zm               ●    3/3              0 Running          3     49        10       n/a        82        12 10.224.0.5     aks-user-41209954-vmss000003     38h
kube-system    csi-azurefile-node-26nxp               ●    3/3              0 Running          3     44        10       n/a        73         7 10.224.0.5     aks-user-41209954-vmss000003     38h
kube-system    kube-proxy-898w6                       ●    1/1              0 Running          1     25         1       n/a       n/a       n/a 10.224.0.5     aks-user-41209954-vmss000003     38h
```

### How to Reproduce the problem?

Create a Qhub on Azure with `min_nodes: 0` in the user node group.

### Versions and dependencies used.

Currently using [my fork](https://github.com/tjcrone/qhub/) of Qhub which upgrades the azurerm to 3.22 so that Qhub will work on the Mac M1. See #1430.
```
$ conda --version
conda 4.14.0
$ kubectl versin
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.23.5
$ qhub --version
0.5.0.dev4+g9de633c
```

### Compute environment

Azure

**Comment by tjcrone** [comment] 2022-09-22 16:53
I think it is worth noting that the worker node group has no problem scaling to zero nodes on Azure. Nodes (instances) terminate after the worker pod leaves, after about 20 minutes which seems like too long really, but the worker scale set will eventually scale to zero. I would expect the user scale set to be able to do the same thing.

**Comment by iameskild** [comment] 2022-09-24 18:12
Hey @tjcrone, thank you for bringing this to our attention! This does indeed seem like strange behavior given what you've said about the `worker` node-group. I will likely need to do some testing on Azure for other reasons, so I will take that opportunity to troubleshoot this as well.

**Comment by iameskild** [comment] 2022-09-28 00:56
Hi @tjcrone, I was able reproduce this issue. I see the `worker` node group scale to 0 but the `user` node groups stays at 1. 

After digging around for a bit, I'm still not sure what the root cause of this issue is. For what it's worth, the pods on the `user` node that I see still are:

```
qhub-prometheus-node-exporter-tb9ps
user-scheduler-8f67c547d-4szr6
user-scheduler-8f67c547d-d7rth
```

More investigated is needed.

**Comment by tjcrone** [comment] 2022-10-05 18:55
Glad to hear that you can reproduce the issue. That's progress! Please let me know if there is anything you would like me to try out I would be happy to help. The fact that the worker cluster will scale to zero is where I would start, trying to figure out what is the difference between that cluster and the user cluster.

This issue affects how we will approach purchasing compute for our deployment, because if we cannot get the user cluster to zero we likely need to pre-purchase at least one virtual machine, or maybe change the machine size for the base user cluster and add another cluster for larger machines.

cc: @daxsoule

**Comment by iameskild** [comment] 2022-10-07 01:07
Hey @tjcrone, unfortunately I have not had the bandwidth to debug this further. 

One guess might be that there is a PVC, or some other resource, that still trying to serve one of the remaining deployments/pods running. 

You could also try manually scaling that node group down to zero (from the Azure portal). Then try launching a user pod and see if the comes back up (and then see if it returns to zero).

**Comment by tjcrone** [comment] 2022-10-07 20:04
I worked on this a bit today, and was able to scale the group to zero in the Azure portal, and it went to zero nodes, but once a user logged in and started an instance, that one instance would not go away. I'm wondering if there might be a bug in the Terraform code because although the minimum nodes for both the user and the worker node pools is set to zero in the Qhub configuration, the two associated JSON files for these resources look different:
```
        "profiles": [
            {
                "name": "Auto created default scale condition",
                "capacity": {
                    "minimum": "0",
                    "maximum": "0",
                    "default": "0"
                },
                "rules": []
            }
```

```
        "profiles": [
            {
                "name": "Auto created default scale condition",
                "capacity": {
                    "minimum": "1",
                    "maximum": "1",
                    "default": "1"
                },
                "rules": []
            }
```
One is set to zero and one to unity. Maybe this a bug in the Terraform scripts or maybe something else I'm not sure. If you have any ideas please let me know. If you would like to poke around on this inside the Portal together sometime that would probably get us to a solution. Thank you!

**Comment by iameskild** [comment] 2022-10-17 16:59
Hi @tjcrone so I was able to push on this a little more and I believe I understand what is going on now. I deleted the `user-scheduler` deployment (deleting this not recommended as it's needed to spin up user's JupyterLab pod) from the cluster and a little while later, the last node in the `user` node group scaled down. This is a bit of a mixed result, for one the autoscaler is working as expected but on the other hand, given that we need the `user-scheduler` pods running, this will prevent a full scale down. 

So although Azure allows node groups to scale down to 0, the `user` node group will always have at least one node running because of the `user-scheduler`. From my perspective, this seems like this is "expected" behavior. The last step for me is to make sure the docs get updated. 

Anyway, let me know if you have other thoughts or findings but otherwise, I will update the docs and close this issue.

**Comment by tjcrone** [comment] 2022-10-17 18:04
Thank you very much for looking into this and finding this result! I agree this appears to be expected behavior considering the need for the user-scheduler pod. This will be a great help regarding our prepurchase plan. Cheers!

**Comment by alimanfoo** [comment] 2022-12-05 17:24
I've also been looking into similar behaviour on GCP. It seems like the `user-scheduler` is intended to improve the packing of user pods into nodes, as described [here](https://z2jh.jupyter.org/en/stable/administrator/optimization.html#optimizations). In other words, if you have some nodes hanging around, you want to avoid having user pods spread out thinly among them, but instead prefer to pack them into the fewest number of nodes possible. This looks like it was created for tuning a large deployment like mybinder.

But an alternative strategy is to get the autoscaler to more aggressively remove unused nodes, so you're unlikely to ever have much if any spare capacity. E.g., on GKE you can set the auto-scaling profile to "optimise utilisation", which means scale down events happen faster. In this case, the `user-scheduler` seems somewhat unnecessary. 

In nebari 2022.11.1 I tried turning it off by editing the file at `stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/values.yaml` after render as follows:

```
scheduling:
  userScheduler:
    enabled: false
```

This does seem to allow scale down to 0.

Just thought I'd share this as our nebari deployment does have long periods of no user activity (nights and weekends) and I would like it to scale down to 0 user and worker nodes.

**Comment by alimanfoo** [comment] 2022-12-05 17:39
In case anyone else stumbles on this also working on GCP, I also found that some kube-system pods were blocking scale down of user and/or worker nodes, particularly kube-dns and metrics-server pods. I seem to have been able to overcome this by doing three things:

* Set the cluster's auto-scaling profile to "optimise utilisation" instead of the default "balanced" (makes scale-down happen faster).
* Change the kube-dns-autoscaler config map as described [here](https://medium.com/plarium-engineering/gke-cluster-scale-zero-tips-49f1d80bee90#annotations:2-tw7nSOEe2htcPQpZB53w).
* Get all system services to run on a specific node pool (i.e., not on user or worker nodes) as described [here](https://samos-it.com/posts/gke-system-services-kube-dns-dedicated-nodepool.html#annotations:ksn0XnS6Ee25VhtM0V1XkA) (e.g., use the "general" node pool).

**Closed** 2023-09-18 16:29 UTC
Labels: type: bug 🐛, provider: Azure, needs: investigation 🔍

**Comment by rsignell** [comment] 2024-04-09 11:38
Is there any update here?  Is it still not possible to scale users & dask workers to 0 on Azure?

**Comment by aktech** [comment] 2024-04-09 13:07
As per @Adam-D-Lewis 

>It should be possible. I support a client on azure and the dask worker nodes scale to zero at a minimum.  Is check if some pods like the user scheduler are running on those nodes preventing them from scaling to 0.

@rsignell What version are you referring to? In the recent versions we've been moving things to general need to avoid getting things scheduled on nodes, that could scale to 0.
