### ISSUE TITLE
[ENH] - Add `local` support for Mac

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1405] opened 2022-08-18 18:30 UTC
### Feature description

It would be nice, as developers, to develop on Mac (and Windows) using a `local` (kind) deployment.

### Value and/or benefit

Currently `local` deployments are only available for Linux. Adding this would allow those with Macs to develop and prototype more quickly the current workarounds ([see dev docs](https://docs.qhub.dev/en/latest/source/dev_guide/minikube.html#minikube-on-aws)). 

### Anything else?

Affects all Macs (Apple Silicon + Intel).

**Comment by iameskild** [comment] 2022-08-18 18:33
I am currently able to partially deploy on Mac ([see branch `kind_on_mac`](https://github.com/Quansight/qhub/tree/kind_on_mac)). Unfortunately this solution is only partially and quite "hacky". More work will be needed before this is fully usable.

**Comment by iameskild** [comment] 2023-01-28 02:01
So far I have tried (or researched) the following with no success:
- UTM virtual machine
- virtualbox virtual machine
  - last time I was reading about this, it wasn't possible to run on Apple Silicon (M1/M2) macs but this [might have changed ](https://osxdaily.com/2022/10/22/you-can-now-run-virtualbox-on-apple-silicon-m1-m2/)and I will need to give this another try.

**Comment by kcpevey** [comment] 2023-08-28 17:19
Blocked by #1950

**Comment by marcelovilla** [comment] 2024-04-22 16:58
The issue around Nebari not working locally on a `kind` cluster on macOS/Windows stems from the fact that Docker containers are not executed natively but rather in a VM. Thus, the container networks are not exposed and cannot be reached from the host.

There are a couple of options we can try to be able to deploy Nebari locally on macOS/Windows:

* Configure [Extra Port Mappings](https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings) to port forward the relevant nodes (probably the load balancer) and configure an [Ingress Controller](https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings) using traefik.
* Try a tool like https://github.com/chipmk/docker-mac-net-connect, which allows for direct connections to the containers via their IP address.

**Comment by viniciusdc** [comment] 2024-04-22 17:49
seems interesting as an option with Vagrant and Kubernetes https://ugurakgul.medium.com/creating-a-local-kubernetes-cluster-with-vagrant-ba591ab70ee2

**Comment by viniciusdc** [comment] 2024-04-22 17:51
from @dcmcand https://github.com/techiescamp/vagrant-kubeadm-mac-silicon

**Comment by aktech** [comment] 2024-05-08 19:45
I have got it working on my Mac M1. Here are the docs: https://github.com/nebari-dev/nebari-docs/pull/454

<img width="1920" alt="Screenshot 2024-05-08 at 3 09 16 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/7c9ba32f-98ad-41fe-989a-e2b4276b9ce8">
<img width="1920" alt="Screenshot 2024-05-08 at 3 09 37 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/6fce4b06-4544-46c8-bb69-51cf177ebea1">
<img width="1920" alt="Screenshot 2024-05-08 at 3 09 02 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/5cbfb02f-8a40-48e1-94d1-78a69233ae39">





This what my nebari config looks like:

```yaml
provider: local
namespace: dev
nebari_version: 2024.5.1rc1
project_name: local-dev
domain: nebari.iakte.ch
ci_cd:
  type: none
terraform_state:
  type: remote
security:
  keycloak:
    initial_root_password: <SANITIZED>
    overrides:
      image:
        repository: quay.io/aktech/keycloak
        tag: 15.0.2
  authentication:
    type: password

default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:m1-image
  jupyterlab: quay.io/nebari/nebari-jupyterlab:m1-image
  dask_worker: quay.io/nebari/nebari-dask-worker:m1-image

jhub_apps:
  enabled: true

argo_workflows:
  enabled: false

conda_store:
  image: quay.io/aktech/conda-store-server
  image_tag: sha-558beb8
theme:
  jupyterhub:
    hub_title: Nebari - local-dev
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs/welcome">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    hub_subtitle: Your open source data science platform, hosted
certificate:
  type: lets-encrypt
  acme_email: <SANITIZED>
```

Relevant issues:
- https://github.com/nebari-dev/nebari/issues/2454
- https://github.com/conda-incubator/conda-store/issues/821

Relevant PRs:
- https://github.com/nebari-dev/keycloak-containers/pull/1
- https://github.com/nebari-dev/nebari-docker-images/pull/141
- https://github.com/nebari-dev/nebari-docs/pull/454

**Comment by nkaretnikov** [comment] 2024-05-16 19:06
@aktech Is your M1 a laptop or a mini/server? How stable is it when you're running it? Is it useable at all? I have a 10-core M1 laptop with 32 gigs of RAM. Using the new docs/config above, I managed to deploy it by putting the domain in the hosts file (`172.18.1.100 nebari.example.com`) and installing/enabling `docker-mac-net-connect`. Then the laptop fans started spinning very fast and the cluster crashed and never recovered, which was after starting JupyterLab and attempting to build a single empty conda-store env. So it looks like it has limited usefulness on a laptop unless there's a way to reduce resource usage of the K8s cluster. Thoughts?

**Comment by marcelovilla** [comment] 2024-05-16 20:04
@nkaretnikov I just tried Amit's config now on a 8-core M1 with 32GB and was able to spin a small Jupyter server up and create a simple conda environment with numpy on it. I think the local cluster has already some memory restrictions because I was not able to spin a medium size server up.

![image](https://github.com/nebari-dev/nebari/assets/36754005/6b30da9c-2795-414d-a727-34083b7d1ba3)

**Comment by nkaretnikov** [comment] 2024-05-18 17:51
OK, turns out there are a bunch of issues on Mac with Docker. So I think the stability/crashes/disconnects were solved by me updating everything to latest, but I also didn't test extensively:
- I had to update Docker Desktop
- I had to install K8s via Docker Desktop instead of using minikube with brew (it can be done via the settings in the UI)
- I had to update macOS to latest because there were crashes in Virtual Machine Service, which are related to Linux kernel support. Before that, I also saw high CPU usage by this service when running Docker
- I had to create this symlink because Docker no longer creates it and terraform cannot find the socket otherwise:
```
sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
```

However, I still cannot get argo workflows working. These are disabled in the config provided by Amit. I needed them for my work, so I set them to true, but then I saw that the nebari-workflow-controller was in the failed state trying to pull the image, so I attempted to do (this image is available on quay):

```
default_images:
...
  nebari_workflow_controller: quay.io/nebari/nebari-workflow-controller:m1-image
```

But it's not possible to set this image via the config because the key is not supported. So I patched this Python file instead:

`./lib/python3.10/site-packages/_nebari/constants.py`:

```
DEFAULT_NEBARI_WORKFLOW_CONTROLLER_IMAGE_TAG = "m1-image"
```

This seemed to solve the problem with the image pull, but the workflows still immediately fail. I did check a bunch of logs in various pods, but I didn't find anything. Not sure where it's supposed to be logged if at all. It's still possible that the change above is not sufficient to use this image correctly. And yes, I did add relevant permissions for my user to be able to use argo in Keycloak.

If someone can get argo workflows working (scheduling a notebook via the JLab UI), let me know. But for now, I'm going to use the cloud again because it's not clear how much more work is needed here.

**Comment by aktech** [comment] 2024-05-29 14:28
> @aktech Is your M1 a laptop or a mini/server? How stable is it when you're running it? Is it useable at all? I have a 10-core M1 laptop with 32 gigs of RAM. Using the new docs/config above, I managed to deploy it by putting the domain in the hosts file (172.18.1.100 nebari.example.com) and installing/enabling docker-mac-net-connect. Then the laptop fans started spinning very fast and the cluster crashed and never recovered, which was after starting JupyterLab and attempting to build a single empty conda-store env. So it looks like it has limited usefulness on a laptop unless there's a way to reduce resource usage of the K8s cluster. Thoughts?

I have a M1 Pro laptop (32GB, 10 cores). It is very stable for me. I have conda environment built with packages required create apps. I never had a cluster crash. Do you have anything else running other than kind cluster?

I am using docker desktop 4.30.0 (149282)

**Comment by aktech** [comment] 2024-05-29 14:30
>However, I still cannot get argo workflows working. These are disabled in the config provided by Amit. I needed them for my work, so I set them to true, but then I saw that the nebari-workflow-controller was in the failed state trying to pull the image, so I attempted to do (this image is available on quay):

I should have mentioned that, I didn't needed argo, so didn't bothered adding it to config.

**Comment by aktech** [comment] 2024-05-29 14:31
> @aktech Yeah, ignore the crash issue. I think it was resolved by updating everything to latest. I'm now more interested in how to get argo-workflows working locally. Have you tried that? They are disabled in your original config.

I can give it a try, let me try the m1-image you shared above.

Also, apologies for the late reply.

**Comment by aktech** [comment] 2024-05-29 15:03
I deployed argo with the latest image `2024.6.1rc3`, it deployed successfully. The notebook scheduling didn't wor. Looks like TLS verification failed while connecting to the API, which is expected as I am running it locally without proper certs. We would probably need to toggle TLS verification to avoid this. Is this what you saw as well?

<img width="1067" alt="Screenshot 2024-05-29 at 4 01 35 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/8b533d51-9ace-4509-a7ea-cbedb1ed2111">

**Comment by nkaretnikov** [comment] 2024-05-29 15:07
I cannot recall at this point, but I agree that fixing the cert issue would be a good first step to resolving this.

**Comment by krassowski** [comment] 2024-05-29 15:17
I see the exact same certificate error, c-f https://github.com/nebari-dev/argo-jupyter-scheduler/pull/10#issuecomment-2122616224. I tried to disable SSL verification but only got me half way thought (the error message changed but did not disappear)

If anyone wants to pick up: https://github.com/nebari-dev/argo-jupyter-scheduler/compare/main...krassowski:argo-jupyter-scheduler:km-papermill-error-2

**Comment by aktech** [comment] 2024-05-29 16:03
That's a good starting point, thanks @krassowski do you recall what was the new error message?

**Comment by krassowski** [comment] 2024-05-29 16:54
See https://github.com/nebari-dev/argo-jupyter-scheduler/pull/10#issuecomment-2132884289 (but maybe it is me issue and I have something misconfigured - so maybe the changes linked above are sufficient - though we need to ensure to only apply them when running a local deployment, so possibly something controlled by an environment variable)

**Comment by aktech** [comment] 2024-05-30 11:37
I have got the notebook scheduler working after setting up real valid certs in my local deployment. I can confirm it's certainly an ssl issue.

## Completed Pods

<img width="1919" alt="Screenshot 2024-05-30 at 12 33 35 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/0972b41c-5c8f-45f0-9223-2ac6a54a2919">


## Completed Job
<img width="1116" alt="Screenshot 2024-05-30 at 12 33 22 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/ba1e620f-81db-4727-9686-acbdc9cfb15a">

**Comment by aktech** [comment] 2024-05-30 12:09
I shared this in slack, I think it might be useful for others as well:

>Local deployment with lets encrypt certs: (without certs some things do not work out of the box, like argo notebook scheduler, etc)

>For anyone interested: . You can setup let's encrypt certs with DNS challenge locally (if you have a domain or can use a subdomain in quansight domains), this basically verifies that you control the domain, by using domain provider's API token, provided by you to let's encrypt. I think its definitely worth setting it up to get a full production environment locally. Here is the branch for setting it up, if anyone want to try: https://github.com/nebari-dev/nebari/compare/dns-challenge?expand=1 (You need to create an API token from cloudflare for the domain you're using)

>We should consider adding the support natively. It's specially useful for Nebari deployments with non-public IP addresses (like inside a private network).

<img width="773" alt="Screenshot 2024-05-30 at 12 40 56 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/b3eb6c72-5f72-4d4f-9485-b4e1d09bf8e2">

**Comment by marcelovilla** [comment] 2024-08-01 15:48
Thanks to @aktech we can now deploy on Mac! Should we keep this issue open or close it for now and open a specific one for windows?

**Comment by kcpevey** [comment] 2024-08-01 17:12
@marcelovilla at this point, is there any special setup required to deploy locally on mac?

**Comment by marcelovilla** [comment] 2024-08-02 13:52
@kcpevey there are two things that need to be configured:

1. We need to use a specific ARM image for Keycloack
2. We need to setup https://github.com/chipmk/docker-mac-net-connect so the container IPs are exposed.

There's [a PR](https://github.com/nebari-dev/nebari-docs/pull/454/files) outlining these two steps.

I'm happy to help you deploy it locally if you ever need to.

**Comment by marcelovilla** [comment] 2024-08-02 13:54
I edited the title of this issue so it's only about local support for Mac. We can open another specific issue for Windows when/if we think it's relevant.

**Closed by marcelovilla** 2024-08-02 13:54 UTC
Labels: area: user experience 👩🏻‍💻, type: maintenance 🛠, needs: investigation 🔍, area:developer-experience 👩🏻‍💻, area: docker 🐋, impact: medium 🟨

**Comment by kcpevey** [comment] 2024-08-02 14:17
Thanks @marcelovilla I was just wanting to make sure we had documentation on the "how", so it looks like that's all taken care of :) 

The docs are now published [here](https://www.nebari.dev/docs/how-tos/nebari-local#exposing-container-network-for-macos).
