### ISSUE TITLE
ENH - Add JupyterHub Grafana dashboards

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#757] opened 2021-08-11 14:21 UTC
In an effort to improve monitoring, I'm looking into using https://github.com/jupyterhub/grafana-dashboards to set up some dashboards to monitor the jupyterhub deployment in Qhub.

**Comment by Adam-D-Lewis** [comment] 2021-11-15 19:42
This issue is still on the to do list, but I don't currently have time to make progress on it.  We do have grafana as part of qhub, but no dashboards that monitor jupyterlab.

As far as time to implement this, it's hard to estimate since I'm not familiar with some of the technologies there (jsonnet).  I'd guess like ~32 hours, but again, that could be too much or too little

**Comment by trallard** [comment] 2023-01-12 18:21
This is a duplicate of #1481 and #1127 closing in favour of the others

**Comment by Adam-D-Lewis** [comment] 2023-04-07 19:45
Closing in favor of https://github.com/nebari-dev/nebari/issues/1481

**Closed** 2024-03-05 15:32 UTC
Labels: type: enhancement 💅🏼, needs: discussion 💬, type: duplicate 👯‍♀️
