### ISSUE TITLE
[BUG] - `qhub destroy` fails for Google Cloud Platform

### ISSUE THREAD

**Issue by HarshCasper** [nebari-dev/nebari#1413] opened 2022-08-22 17:02 UTC
### OS system and architecture in which you are running QHub

macOS M1

### Expected behavior

`qhub destroy` should work properly.

### Actual behavior

It fails with:

```sh
  File "/Users/harshcasper/qhub/env/bin/qhub", line 8, in <module>
    sys.exit(main())
  File "/Users/harshcasper/qhub/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/Users/harshcasper/qhub/qhub/cli/__init__.py", line 51, in cli
    args.func(args)
  File "/Users/harshcasper/qhub/qhub/cli/destroy.py", line 38, in handle_destroy
    destroy_configuration(config)
  File "/Users/harshcasper/qhub/qhub/destroy.py", line 173, in destroy_configuration
    stage_outputs = gather_stage_outputs(config)
  File "/Users/harshcasper/qhub/qhub/destroy.py", line 66, in gather_stage_outputs
    input_vars=input_vars.stage_07_kubernetes_services(stage_outputs, config),
  File "/Users/harshcasper/qhub/qhub/stages/input_vars.py", line 261, in stage_07_kubernetes_services
    "realm_id": stage_outputs["stages/06-kubernetes-keycloak-configuration"][
KeyError: 'realm_id'
```

### How to Reproduce the problem?

1. Create a QHub deployment on GCP.
2. Run `qhub destroy` on your QHub configuration file.

### Versions and dependencies used.

QHub: v0.4.4rc3

### Compute environment

GCP

**Comment by viniciusdc** [comment] 2022-08-23 13:53
Hi @HarshCasper, this issue normally happens when:
- The first deployment did not fully complete
- Or, when you run `qhub destroy` twice

Would you mind trying to reproduce this again?

**Comment by viniciusdc** [comment] 2022-08-23 16:07
> I also had `qhub destroy` on GCP fail for me (v0.4.3). This was the end of my logs:
> 
> ```
> [terraform]: Destroy complete! Resources: 1 destroyed.
> [terraform]: INFO:qhub.provider.terraform:terraform destroy took 5.309 [s]
> INFO:qhub.provider.terraform:terraform=/var/folders/_m/567tmc5s4csdf_0r8x23mp480000gn/T/terraform/1.0.5/terraform output directory=stages/01-terraform-state/gcp
> INFO:qhub.provider.terraform:terraform output took 0.898 [s]
> INFO:qhub.destroy:destroying QHub took 833.955 [s]
> ERROR:qhub.destroy:Stage=stages/08-qhub-tf-extensions failed to fully destroy
> ERROR:qhub.destroy:Stage=stages/07-kubernetes-services failed to fully destroy
> ERROR:qhub.destroy:Stage=stages/05-kubernetes-keycloak failed to fully destroy
> ERROR:qhub.destroy:Stage=stages/04-kubernetes-ingress failed to fully destroy
> ERROR:qhub.destroy:Stage=stages/03-kubernetes-initialize failed to fully destroy
> ERROR:qhub.destroy:ERROR: not all qhub stages were destroyed properly. For cloud deployments of QHub typically only stages 01 and 02 need to succeed to properly destroy everything
> ```
> 
> Not sure if there was error that got lost somewhere in the terraform output.

Hi @kcpevey, this is an expected message, it means that all infrastructure-related resources managed directly by terraform were removed, but some resources created by the cloud provider (sometimes a network connection, security groups, etc) were not removed due to Terraform not knowing any information about these. 

So, in short, that message means that you should confirm manually that there is no lingering resource in the cloud side.

**Comment by iameskild** [comment] 2023-09-11 16:25
The `nebari destroy` is working for GCP. Closing this issue.

**Closed by iameskild** 2023-09-11 16:25 UTC
Labels: type: bug 🐛, area: terraform 💾, area: integration/keycloack
