### ISSUE TITLE
[BUG] - 2 New Notebook Kernels Show Up after creating R environment

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2272] opened 2024-02-22 16:31 UTC
### Describe the bug

I created a global environment called "R" in conda store.  I requested `r-irkernel` and `r-essentials` dependencies.  It seems that ipykernel is added by default.  I believe due to r-irkernel and ipykernel being installed we get 2 new kernels showing up from the jupyterlab interface (screenshot below), one which expects python code and one which expects R code (screenshot below).

![image](https://github.com/nebari-dev/nebari/assets/23342526/a084b91f-c6fb-41fa-97fe-79b84b293314)

### Expected behavior

Only 1 new kernel.  Don't add ipykernel if r-irkernel is installed.

### OS and architecture in which you are running Nebari

LInux

### How to Reproduce the problem?

See above

### Compute environment

None

**Comment by dharhas** [comment] 2024-02-22 16:41
@krassowski would you know anything about how this works. I assume it is related to nb-conda-kernals.

**Comment by dharhas** [comment] 2024-02-22 16:44
ah yes, that is probably true. it is a setting in config to add ipykernel to all envs so that it will show up in jupyter.

**Comment by dharhas** [comment] 2024-02-22 16:58
ideally we should also use an R icon.

**Comment by krassowski** [comment] 2024-02-22 16:59
It's in conda-store setting, not of conda-nb-kernels:

https://github.com/nebari-dev/nebari/blob/5463e8df9e8d53a266a7b9d3d4e27353ec43c40b/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py#L33

I guess opt-out would also need to be implemented in conda-store?

**Comment by krassowski** [comment] 2024-02-22 17:00
Unless you would want to opt-out globally then this could be a nebari setting.

**Comment by dharhas** [comment] 2024-02-22 17:01
Well the issue is that we only want to opt out if another kernel like irkernel is requested. Not sure how we do this.

**Comment by krassowski** [comment] 2024-02-22 17:05
Interestingly the icon does show up for me (see last two icons in both rows):

![icon-shows-up-for-me](https://github.com/nebari-dev/nebari/assets/5832902/fee37ec3-490b-4cf1-805b-d679df33d591)

It may be more subtle issue depending on how the environment is created (global vs personal).

**Comment by dcmcand** [comment] 2024-02-22 20:01
Having looked into this, it would definitely need fixed on the conda-store side. There are a couple of ways that I could think to approach this.

1. Add a new config option for jupyterlab support. That would automatically add ipykernel unless irkernel is requested. This has the advantage that we could get specific with our logic without complicating the conda_include_packages config option. It would be pretty straightforward to implement. The disadvantage is we are hard coding usecase specific logic. That is generally not good, but may be ok here since jupyterlab is used so widely.

2. Add an option to the api route that creates environment to ignore auto included packages. This option could then be exposed in the ui. The default would be to include the automatic packages, but a user could choose to override that. This has the advantage of greater flexibility, we aren't writing a single purpose solutions, but users could also get themselves into trouble and could create environments that did not have packages that were set as auto include in the config. I don't think that this would be particularly difficult to implement, but would require ui work as well as server side work.

**Comment by kcpevey** [comment] 2024-02-22 20:16
I couldn't transfer this issue to conda-store since its a different org so I had to open up a new one - https://github.com/conda-incubator/conda-store/issues/769. I'll close this one.

**Closed by kcpevey** 2024-02-22 20:16 UTC
Labels: type: bug 🐛, needs: triage 🚦
